linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
osx: &osx
   os: osx
   language: generic
env:
  - BINCRAFTERS_TEMPLATE="header-only"
  
install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
